spring.application.name=validacion_hsm


#==========================
# HSM CONFIGURATION
#==========================
hsm.realsec.provider.name=RealsecPKCS11Provider
hsm.realsec.config.path=D:/validador/config.txt
#hsm.realsec.config.path=D:/HSM/RealsecCoB/config.txt
#hsm.realsec.config.pathserver=/Data8/arc/bnmx/src/processing/prod/validador_hsm/drivers/config.txt
hsm.realsec.config.pathserver=D:/validador/config.txt
hsm.realsec.type=RealsecKS
hsm.realsec.pin=Filt3r5*


#==================
# JWS
#==================
jws.alg=RS256
jws.cty=JWT
jws.iss=arc
jws.sub=arc

#==================
# JWE
#==================
jwe.alg=RSA1_5
jwe.enc=A256GCM
jwe.cty=JWT
